// const categories = [
//   { width: '98%', name: 'Air Fresheners' },
//   { width: '32%', name: 'Baby Products' },
//   { width: '65%', name: 'Bathing Soap & Shower Gels' },
//   { width: '58%', name: 'Bathroom Cleaners' },
//   { width: '38%', name: 'Beers' },
//   { width: '48%', name: 'Cereals' },
//   { width: '48%', name: 'Cleaning Tools' },
//   { width: '58%', name: 'Coffee, Tea & Cocoa' },
//   { width: '38%', name: 'Cooking ingredients' },
//   { width: '98%', name: 'Deodorant & Body Sprays' },
//   { width: '32%', name: 'Diapers' },
//   { width: '65%', name: 'Dishwashing' },
//   { width: '58%', name: 'Disposables' },
//   { width: '38%', name: 'Drinks' },
//   { width: '48%', name: 'Feeding' },
//   { width: '48%', name: 'Food' },
//   { width: '58%', name: 'Grains' },
//   { width: '38%', name: 'Hair Care' },
//   { width: '98%', name: 'Household Cleaning' },
//   { width: '32%', name: 'Hygiene' },
//   { width: '65%', name: 'Juices' },
//   { width: '58%', name: 'Laundry' },
//   { width: '38%', name: "Men's Shaving" },
//   { width: '48%', name: 'Non Alcoholic Drinks' },
//   { width: '48%', name: 'Noodles' },
//   { width: '58%', name: 'Oral Care' },
//   { width: '38%', name: 'Pasta' },
//   { width: '98%', name: 'Plastic & Paper Products' },
//   { width: '32%', name: 'Red wine' },
//   { width: '65%', name: 'Sanitizers' },
//   { width: '58%', name: 'Shampoo' },
//   { width: '38%', name: 'Storage bags' },
//   { width: '48%', name: 'Toilet Papers & Wipes' },
//   { width: '48%', name: 'Trash bags' },
//   { width: '58%', name: 'Vodka' },
//   { width: '38%', name: 'Whiskey' },
// ];
